### ISSUE TITLE
Avoid sources on facet edges

### ISSUE THREAD

**Issue by duyhoang-astro** [lofar-astron/factor#207]
Does anyone know which package controls the facet edges? And which version is required for the package? I have some sources that lay on the facet edges, even though check_edges is set to default (# check_edges = True). Below is an example image,

![image](https://cloud.githubusercontent.com/assets/11923709/24787594/d8348938-1b9b-11e7-99d1-eee9967fb53b.png)

Thanks.

**Comment by darafferty** [comment]
Shapely (https://github.com/Toblerity/Shapely) is needed for adjustment of the facet edges.

**Comment by AHorneffer** [comment]
Is the source actually in the sky-model that Factor uses for the faceting? If Factor doesn't know that there is a source then it won't bother trying to avoid the source.
If you don't know which file is used, you can explicitly specify it with the `faceting_skymodel` option.

**Comment by duyhoang-astro** [comment]
@darafferty: I tested a few commands provided in the link. Shapely seems to work fine without any errors.

@AHorneffer: Below is another source on the facet boundaries. The red region is new facet layout, the green one was created previously. In the green region didn't cross the source, but the red one does. So, the skymodel does contain this source, but due to some reason Shapely does not work properly inside Factor at the moment (with my environment settings)?

![image](https://cloud.githubusercontent.com/assets/11923709/24860306/45a5f3f8-1df4-11e7-8ca2-c684adcaf7fb.png)

One thing I noticed was that there was an update on Python packages here, which caused problems with Pybdsm. But this was fixed by rolling back the updated Python packages. Currently it's Python 2.7.5 ...

**Comment by duyhoang2014** [comment]
I have rerun Factor with similar parsets. The facet edges avoid sources correctly. Perhaps some dependency has been changed/updated (which often happens with our cluster). I still don't know what exactly causes the issue, but facet layout is correct now...

**Comment by AHorneffer** [comment]
Is this solved now? Or is this still an open issue?

**Comment by duyhoang-astro** [comment]
@AHorneffer: I don't know if this relates to the number of facet (ndir_max). But when I changed it (ndir_max), the facet layout does not cross the source. So, I used the new layout (with different ndir_max).

I haven't tested with the current version of FACTOR. So, I am not sure if this still happens... I might close this issue for now. Please re-open if needed.
